*IMPORTAR LA LIBRERIA*

##TRAER EL ARCHIVO DE CSV

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_csv = pd.read_csv("C:\\Users\\juan1\\Downloads\\dataset_pandas.csv")

In [5]:
df_csv

,id,edad,email,genero,estado,IMC
0,6c7984c9-270d-4dee-b21e-8460ba65a683,75.0,salsobrook0@amazon.co.uk,Masculino,Florida,26.7
1,45b54530-317e-4c64-b718-597990ff6fd9,84.0,haddenbrooke1@parallels.com,Masculino,Illinois,30.6
2,87ef46d9-e9c8-4ba3-8965-5553b48ad2d9,NaN,ikynge2@cnbc.com,Femenino,Hawaii,26.7
3,33267565-7115-4bec-9dc1-3e5057412d10,57.0,jsnoad3@globo.com,Masculino,California,29.2
4,3cddc250-e992-4a30-8097-f1422761b7be,59.0,kstringer4@sakura.ne.jp,Femenino,Utah,27.5
...,...,...,...,...,...,...
1000,02568917-9a13-4f6b-ba09-5d664e8069f6,34.0,tmoorhousero@live.com,Masculino,Louisiana,25.4
1001,7ddaf233-2a46-429a-b4be-f8ff5917d299,47.0,sarstingallrp@ibm.com,Masculino,District of Columbia,26.4
1002,889d5238-aa0c-4717-b841-962d09eeca9c,76.0,mmcgroartyrq@fastcompany.com,Femenino,Florida,18.3
1003,bacda779-4383-435c-a9d9-c8c8c5b28bd7,57.0,sbussrr@fastcompany.com,Masculino,New York,24.5
1004,Información tomada de: Servicio Nacional de Salud,2023.0,NaN,NaN,NaN,NaN

Hay veces que la ultima fila tiene un resumen o un total de las operaciones de todas las columnas. Podemos usar pandas para quitarlo.

In [7]:
df_csv = pd.read_csv("C:\\Users\\juan1\\Downloads\\dataset_pandas.csv", skipfooter=1)

df_csv

C:\Users\juan1\AppData\Local\Temp\ipykernel_12612\3362957902.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  df_csv = pd.read_csv("C:\\Users\\juan1\\Downloads\\dataset_pandas.csv", skipfooter=1)

,id,edad,email,genero,estado,IMC
0,6c7984c9-270d-4dee-b21e-8460ba65a683,75.0,salsobrook0@amazon.co.uk,Masculino,Florida,26.7
1,45b54530-317e-4c64-b718-597990ff6fd9,84.0,haddenbrooke1@parallels.com,Masculino,Illinois,30.6
2,87ef46d9-e9c8-4ba3-8965-5553b48ad2d9,NaN,ikynge2@cnbc.com,Femenino,Hawaii,26.7
3,33267565-7115-4bec-9dc1-3e5057412d10,57.0,jsnoad3@globo.com,Masculino,California,29.2
4,3cddc250-e992-4a30-8097-f1422761b7be,59.0,kstringer4@sakura.ne.jp,Femenino,Utah,27.5
...,...,...,...,...,...,...
999,2c54f71c-23f8-46e6-abdf-05fc78e717a3,49.0,ldelavaletteparisotrn@booking.com,Femenino,California,25.7
1000,02568917-9a13-4f6b-ba09-5d664e8069f6,34.0,tmoorhousero@live.com,Masculino,Louisiana,25.4
1001,7ddaf233-2a46-429a-b4be-f8ff5917d299,47.0,sarstingallrp@ibm.com,Masculino,District of Columbia,26.4
1002,889d5238-aa0c-4717-b841-962d09eeca9c,76.0,mmcgroartyrq@fastcompany.com,Femenino,Florida,18.3
1003,bacda779-4383-435c-a9d9-c8c8c5b28bd7,57.0,sbussrr@fastcompany.com,Masculino,New York,24.5